apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zerofiltretech-uat
  name: zerofiltretech-uat
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      app: zerofiltretech-uat
  template:
    metadata:
      labels:
        app: zerofiltretech-uat
    spec:
      containers:
        - name: zerofiltretech-uat
          image: imzerofiltre/zerofiltretech:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: zerofiltretech-uat
  name: zerofiltretech-uat
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: zerofiltretech-uat
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zerofiltretech-uat
  namespace: zerofiltretech-uat
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "uat.zerofiltre.tech"
      http:
        paths:
          - path: /
            backend:
              serviceName: zerofiltretech-uat
              servicePort: 80
